/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InsightsIdRouteImport } from './routes/insights.$id'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsIdRoute = InsightsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => InsightsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/insights': typeof InsightsRouteWithChildren
  '/services': typeof ServicesRoute
  '/insights/$id': typeof InsightsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/insights': typeof InsightsRouteWithChildren
  '/services': typeof ServicesRoute
  '/insights/$id': typeof InsightsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/insights': typeof InsightsRouteWithChildren
  '/services': typeof ServicesRoute
  '/insights/$id': typeof InsightsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/insights' | '/services' | '/insights/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/insights' | '/services' | '/insights/$id'
  id: '__root__' | '/' | '/insights' | '/services' | '/insights/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InsightsRoute: typeof InsightsRouteWithChildren
  ServicesRoute: typeof ServicesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/$id': {
      id: '/insights/$id'
      path: '/$id'
      fullPath: '/insights/$id'
      preLoaderRoute: typeof InsightsIdRouteImport
      parentRoute: typeof InsightsRoute
    }
  }
}

interface InsightsRouteChildren {
  InsightsIdRoute: typeof InsightsIdRoute
}

const InsightsRouteChildren: InsightsRouteChildren = {
  InsightsIdRoute: InsightsIdRoute,
}

const InsightsRouteWithChildren = InsightsRoute._addFileChildren(
  InsightsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InsightsRoute: InsightsRouteWithChildren,
  ServicesRoute: ServicesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
